### PR TITLE
Updating marp and using release binaries.

### PR DESCRIPTION
**Pull request by ck3mp3r**
After waiting for about 30 minutes to build marp as per old derivation I decided to see if I could just use the pre-built binaries.

Feel free to use this PR, request changes etc. if you are interested.

Hope this helps someone.

### CODE REVIEW

**Comment by GuillaumeDesforges** [comment]
Thank you for your contribution @ck3mp3r ! It is most welcome.

This should definitely speed up things :rocket: 
I don't know if pre-built binaries have specific limitations, though I expect they have none.

I tried running your PR but I had an error.

```
$ nix shell github:ck3mp3r/nix-marp
error: hash mismatch in file downloaded from 'https://github.com/marp-team/marp-cli/releases/download/v3.4.0/marp-cli-v3.4.0-mac.tar.gz':
         specified: sha256:0aq1i51ygzx9981v1xwfgld8bq1mw6yh27wyprckm488qyr5xyfv
         got:       sha256:0jy4cfmrajyxill6spgs194jkbsmrkhvb4n4ncfdi2ynsa97bgp9
```

My system is `x86_64-linux`.

Would you be able to check if you get the same issue?

FYI, I upstreamed marp-cli to nixpkgs: https://github.com/NixOS/nixpkgs/pull/248107

**Comment by ck3mp3r** [comment]
> ```
> $ nix shell github:ck3mp3r/nix-marp
> error: hash mismatch in file downloaded from 'https://github.com/marp-team/marp-cli/releases/download/v3.4.0/marp-cli-v3.4.0-mac.tar.gz':
>          specified: sha256:0aq1i51ygzx9981v1xwfgld8bq1mw6yh27wyprckm488qyr5xyfv
>          got:       sha256:0jy4cfmrajyxill6spgs194jkbsmrkhvb4n4ncfdi2ynsa97bgp9
> ```
> 
> My system is `x86_64-linux`.
> 
> Would you be able to check if you get the same issue?
> 
> FYI, I upstreamed marp-cli to nixpkgs: [NixOS/nixpkgs#248107](https://github.com/NixOS/nixpkgs/pull/248107)

Ha! nix-prefetch-url bites again :) Will have to check! I'll setup a linux vm and test.

**Comment by ck3mp3r** [comment]
Hi @GuillaumeDesforges can you try now? I was being daft and fell foul of a copy pasta error...

**Comment by GuillaumeDesforges** [comment]
Not working :(

```
gdforj@tosaka:~$ nix shell github:ck3mp3r/nix-marp
gdforj@tosaka:~$ marp --help
bash: /nix/store/bx4vc9zndii82kchkmd6x6spav7scbza-marp-cli/bin/marp: cannot execute: required file not found
gdforj@tosaka:~$ ls /nix/store/bx4vc9zndii82kchkmd6x6spav7scbza-marp-cli/bin/
marp
```

**Comment by ck3mp3r** [comment]
> Not working :(
> 
> ```
> gdforj@tosaka:~$ nix shell github:ck3mp3r/nix-marp
> gdforj@tosaka:~$ marp --help
> bash: /nix/store/bx4vc9zndii82kchkmd6x6spav7scbza-marp-cli/bin/marp: cannot execute: required file not found
> gdforj@tosaka:~$ ls /nix/store/bx4vc9zndii82kchkmd6x6spav7scbza-marp-cli/bin/
> marp
> ```

I'll test in a VM as soon as I can. Might have to tweak the unpackPhase a bit...

**Comment by ck3mp3r** [comment]
@GuillaumeDesforges what linux are you running? Can you run a "file /nix/store/?????/bin/marp" ?
I think it is because the binary isn't statically linked like on the mac... this might not be a solution after all and you might actually be better off with the version you added to nixpkgs...

```
❯ file `which marp`
/nix/store/c4jy2glbxvd3yps2i13l60xd77jfbx7d-marp-cli/bin/marp: Mach-O 64-bit executable arm64
```
On the NixOS VM I'm getting an x86 binary that is dynamically linked to /lib64/ld-linux-x86-64.so.2
So no dice on NixOS for me...

**Comment by GuillaumeDesforges** [comment]
Oh so you are on Mac. For a Nix build to be really portable, you have to patch binaries so they are properly linked.
See https://nixos.wiki/wiki/Packaging/Binaries

I pushed a diff here that fixes the issue I raised above.
https://github.com/GuillaumeDesforges/nix-marp/commit/a12b210

However there is then another issue from the binary:

```
$ ./result/bin/marp --help
pkg/prelude/bootstrap.js:11
            });
            ^

SyntaxError: Unexpected token '}'
    at new Script (node:vm:102:7)
    at readPrelude (node:internal/bootstrap/pkg:29:13)
    at node:internal/bootstrap/pkg:36:18
    at node:internal/bootstrap/pkg:43:4
    at node:internal/bootstrap/pkg:44:2

Node.js v18.5.0
```

I unfortunately don't have enough knowledge to fix this NodeJS build issue.

**Comment by ck3mp3r** [comment]
@GuillaumeDesforges I don't think this type of binary allows for the usual patching... it is after all a binary that runs on both x86 and arm, you notice there aren't any dedicated downloads. The only dedicated downloads are for mac, linux and windows respectively but not the architecture...

**Comment by GuillaumeDesforges** [comment]
I found similar issues reported to `vercel/pkg` which I suppose is what marp used.
https://github.com/vercel/pkg/issues/1971

EDIT: not quite; seems like it's a custom script https://github.com/marp-team/marp-cli/blob/main/scripts/pack.js

EDIT: nvm, they really use pkg
https://github.com/marp-team/marp-cli/blob/04a1bcf6bc850659ae4f8842ca527b4a49436290/package.json#L64C34-L64C56

**Comment by GuillaumeDesforges** [comment]
So I checked the binary. The binary has code like this:

```javascript
(function () {
  var __require__ = require;
  var fs = __require__('fs');
  var vm = __require__('vm');
  function readPrelude (fd) {
    var PAYLOAD_POSITION = '46205192              ' | 0;
    var PAYLOAD_SIZE = '138345620         ' | 0;
    var PRELUDE_POSITION = '184550812             ' | 0;
    var PRELUDE_SIZE = '1059813           ' | 0;
    if (!PRELUDE_POSITION) {
      // no prelude - remove entrypoint from argv[1]
      process.argv.splice(1, 1);
      return { undoPatch: true };
    }
    var prelude = Buffer.alloc(PRELUDE_SIZE);
    var read = fs.readSync(fd, prelude, 0, PRELUDE_SIZE, PRELUDE_POSITION);
    if (read !== PRELUDE_SIZE) {
      console.error('Pkg: Error reading from file.');
      process.exit(1);
    }
    var s = new vm.Script(prelude, { filename: 'pkg/prelude/bootstrap.js' });
    var fn = s.runInThisContext();
    return fn(process, __require__,
      console, fd, PAYLOAD_POSITION, PAYLOAD_SIZE);
  }
  (function () {
    var fd = fs.openSync(process.execPath, 'r');
    var result = readPrelude(fd);
    if (result && result.undoPatch) {
      var bindingFs = process.binding('fs');
      fs.internalModuleStat = bindingFs.internalModuleStat;
      fs.internalModuleReadJSON = bindingFs.internalModuleReadJSON;
      fs.closeSync(fd);
    }
  }());
}());
```

as you can see, position and size of the bytes of the script sources are hard-coded:

```
    var PAYLOAD_POSITION = '46205192              ' | 0;
    var PAYLOAD_SIZE = '138345620         ' | 0;
    var PRELUDE_POSITION = '184550812             ' | 0;
    var PRELUDE_SIZE = '1059813           ' | 0;
```

so patching the binary, which will change the position of the text bytes in the binary, of course breaks it. :facepalm:

**Comment by ck3mp3r** [comment]
Yeah, I am going to refrain from commenting on this particular ecosystem 😄 I try to avoid the languages and tooling associated with it as much as possible...

However, this whole little discourse made me realise I was compiling one of my own tools incorrectly, forgot to create static rust binaries for linux...

I guess this will be solved with your upstream addition of Marp to Nix Packages, so happy to drop this in favour of that... what do you think?

**Comment by GuillaumeDesforges** [comment]
> I guess this will be solved with your upstream addition of Marp to Nix Packages, so happy to drop this in favour of that... what do you think?

This sounds more reasonable. You should hit the cache by using the package on nixpkgs, hence fixing your initial issue.

For future reference: the whole `pkg` thing needs to download a patched NodeJS binary (ref https://github.com/vercel/pkg/issues/765). Since Nix build is sandboxed, there is no internet connection. This is just too much hassle.

Anyways, thanks again @ck3mp3r!
(I got to learn more about how weird the JS ecosystem is and will be)

**Comment by ck3mp3r** [comment]
@GuillaumeDesforges as discussed closing this in favour of the nix package.
Happy to collaborate on other things in future 😃

**Pull request closed without merging**
